---
title: "Topic."
description: |
  Topic of capstone project.
author: Leonardo Torres
date: September 2, 2025
format: pdf
execute:
  warning: false
  message: false
---


### Topic

Advisor: Marc Los Huertos (Environmental Studies at Pomona College)

Area: Environmental Analysis

No weekly meeting time set, most likely Thursdays but still to be decided.

My project will be covering a topic called Planetary boundaries, a terminology that was introduced in 2009 by a scientist called Rockstrum. This work has been in development throughout the past decade with new updates as of last year 2024."The planetary boundaries framework highlights the rising risks from human pressure on nine critical global processes that regulate the stability and resilience of the earth". (Stockholm resilience Center). The 9 boundaries/processes this addresses are climate change (CO2 concentration and Radiative forcing), biosphere integrity (Genetic and Functional), Land-System change, Freshwater Change (Blue and green water), Biogeochemical flows (P and N), Ocean Acidification, Atmospheric Aerosol Loading, Stratospheric Ozone Depletion, Novel Entities. Overall, this framework approaches these 9 processes of the Earth into zones that have a "safe operating zone" where the zone fills up based on how much it is impacted. For example, the climate change zone has passed this safety threshold meaning it is in an area where the earth isn't stable and is being effected negatively in some way meanwhile ocean acidification is just under the threshold. These visual guides can be found at: https://www.stockholmresilience.org/research/planetary-boundaries.html. This website makes a great visual representation of how we can see what state the earth is in different enviornmental causes. Talking to Prof. Los Huertos, we wanted to see if it would be possible to create a interactive data visualization where users can predicate what the Earth threshold/boundary will be at if for example we use 1 million less fresh water gallons for the next 5 years. This will be done through measuring previous data and comparing it to the risk threshold that previous papers have set. This project is really interesting and connects multiple areas of data science but the main concern between Prof. Los Huertos and I are if it will be alot of work. Currently their is a github repo for such code however it is a very large file containing 70/100 HTML code and 30/100 R code. We will have a meeting soon covering this code and seeing if this project is feasible for this semester.
